import type { MDXComponents } from 'mdx/types';
import {
  CodeBlock,
  FeatureCard,
  InfoCallout,
  WarningCallout,
  SuccessCallout,
  TipCallout,
  ApiMethod,
  Step,
  PropertyTable,
  FeatureGrid,
  SectionDivider,
  CodeTabs,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/mdx-components';

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    CodeBlock,
    FeatureCard,
    InfoCallout,
    WarningCallout,
    SuccessCallout,
    TipCallout,
    ApiMethod,
    Step,
    PropertyTable,
    FeatureGrid,
    SectionDivider,
    CodeTabs,
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  };
}
